### ISSUE TITLE
Receiving following error after installation from HACS

### ISSUE THREAD

**Issue by mkopnsrc** [burnnat/ha-hdhomerun#6]
After installing this hdhomerun plugin and adding code to configuration.yaml
hdhomerun:
    sensor:
        - host: 192.168.1.10
Restarted entire HomeAssistant server but sensor doesn't show up. After looking at logs, this is what I saw below. Let me know if I can help in anyway. Thanks.

Logger: homeassistant.core
Source: custom_components/hdhomerun/config_flow.py:5
First occurred: 12:16:16 AM (1 occurrences)
Last logged: 12:16:16 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 100, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hdhomerun/config_flow.py", line 5, in <module>
    from hdhr.adapter import HdhrUtility
  File "/usr/local/lib/python3.7/site-packages/hdhr/adapter.py", line 13, in <module>
    from hdhr.externals import *
  File "/usr/local/lib/python3.7/site-packages/hdhr/externals.py", line 5, in <module>
    import hdhr.libhdhr
  File "/usr/local/lib/python3.7/site-packages/hdhr/libhdhr.py", line 14, in <module>
    library = cdll.LoadLibrary(_FILEPATH)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error loading shared library libhdhomerun.so: No such file or directory

**Comment by burnnat** [comment]
Thanks for the report. From this error it looks like the [libhdhomerun](https://github.com/Silicondust/libhdhomerun) library was not found on your system:

    OSError: Error loading shared library libhdhomerun.so: No such file or directory

Are you running Home Assistant Core or a full Home Assistant installation (formerly Hassio)? Per the [installation instructions](https://github.com/burnnat/ha-hdhomerun/blob/master/info.md#installation) you'll need to get libhdhomerun set up in order for the integration to function.

**Comment by mkopnsrc** [comment]
@burnnat  I'm using the full hassio image on Pi3b. I did ran "apk add libhdhomerun" first then added hdhomerun config in configuration.yaml

**Comment by k-rock** [comment]
I also ran 'apk add libhdhomerun', added config in configuration.. I see the following in my logs:
![Annotation 2020-04-03 082108](https://user-images.githubusercontent.com/15674791/78360021-1fed4e00-7584-11ea-85f9-0a923393d43e.png)

**Comment by disturbed-pixel** [comment]
I'm getting the same as @k-rock and @mkopnsrc (yes the lib is installed) on Ubuntu - hassio

![image](https://user-images.githubusercontent.com/8006858/79365070-0e238780-7f42-11ea-837b-c7cef14c5c3c.png)

**Comment by Nils154** [comment]
If you are running homeassistant core, you need to do something like this:
`sudo docker exec -it homeassistant apk add libhdhomerun`
It installs the library in the docker image.
